name: ci

on:
  push:
  pull_request:

jobs:
  ci-checks-build:
    name: Build for ${{ matrix.idf-version }} target ${{ matrix.chip-target }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        idf-version: ['v4.4.5', 'v5.0.3', "v5.1.1"]
        chip-target: ['esp32']
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        uses: actions/cache@v3
        with:
          path: build/
          key: ${{ runner.os }}-esp-idf-${{ matrix.chip-target }}-${{ matrix.idf-version }}
      -
        name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ matrix.idf-version }}
          target: ${{ matrix.chip-target }}
          path: "."
